"""Add generated content fields to Article model

Revision ID: 9b33eb58e9a5
Revises: 
Create Date: 2025-05-02 21:49:02.915020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b33eb58e9a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('short_summary', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('blog_post', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('short_summary_audio_path', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('blog_post_audio_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'blog_post_audio_path')
    op.drop_column('articles', 'short_summary_audio_path')
    op.drop_column('articles', 'blog_post')
    op.drop_column('articles', 'short_summary')
    # ### end Alembic commands ###
