"""Implement M:N User-Feed relationship

Revision ID: f94821e175d1
Revises: 3a72438d18df
Create Date: 2025-05-02 22:16:33.663166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94821e175d1'
down_revision: Union[str, None] = '3a72438d18df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Skip creating user_feeds table as it seems to exist from a partial run
    # op.create_table('user_feeds',
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.Column('feed_id', sa.Integer(), nullable=False),
    # sa.Column('user_title', sa.String(), nullable=True),
    # sa.Column('subscribed_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('user_id', 'feed_id'),
    # sa.UniqueConstraint('user_id', 'feed_id', name='_user_feed_uc')
    # )
    
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.create_unique_constraint('_feed_url_uc', ['url'])
        batch_op.create_index(batch_op.f('ix_feeds_url'), ['url'], unique=True)
        batch_op.drop_column('user_id')
        
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_feeds_url'))
        batch_op.drop_constraint('_feed_url_uc', type_='unique')

    op.drop_table('user_feeds') # Keep dropping the table on downgrade
    # ### end Alembic commands ###
